# Final Words

This analysis has explored the data wrangling and imputation of groundwater data using a dataset from NASA's JPL. We began by exploring the dataset and wrangling the data to find wells that we could perform data imputation on. We then explored two different methods for imputing data. The ELM method is very involved, and will require further analysis to be validated by this data. This paper has performed much of the data exploration and cleaning required and has laid the groundwork necessary for scaling this analysis to larger datasets. The IDW method was performed and returned reasonable results. The limitations inherent in this approach were evident in the error summary that we generated.

Future analysis on this dataset would stem from further work on converting the ELM method to usable code in R. While outside the scope of this paper, validating this approach will be one of the objectives of the author as part of his Master's thesis. Further error analysis will also be necessary, as this paper only uses two error metrics. Finally, the groundwork is in place for basic analysis of a few wells. Future analyses of this data could include scaling up this effort to include many more wells in the analysis and validation efforts of the ELM method.

